{
 "title": "Main Dashboard",
 "tags": [
  "windows",
  "hyper-v",
  "vm",
  "telegraf"
 ],
 "time": { "from": "2022-06-17T09:45:10.111Z", "to": "2022-06-17T09:46:09.721Z" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"win_system\" WITH KEY = \"host\""
   },
   {
    "name": "csv_volume",
    "label": "Cluster Volume",
    "query": "SHOW TAG VALUES FROM \"cluster_csv_filesystem\" WITH KEY = \"instance\" WHERE host =~ /$hostname/"
   },
   {
    "name": "virtual_machine",
    "label": "Virtual Machine",
    "query": "SHOW TAG VALUES FROM \"hyperv_vid\" WITH KEY = \"instance\" WHERE \"host\" =~ /^$hostname$/"
   },
   {
    "name": "vm_disk",
    "label": "VM Disk",
    "query": "SHOW TAG VALUES FROM \"hyperv_storage\" WITH KEY = \"instance\" WHERE \"host\" =~ /^$hostname$/"
   },
   {
    "name": "virtual_switch",
    "label": "Virtual Switch",
    "query": "SHOW TAG VALUES FROM \"hyperv_vswitch\" WITH KEY = \"instance\" WHERE host =~ /$hostname/"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Processors Running",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: vCPUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hyperv_hypervisor",
     "select": [
      [
       { "params": [ "Logical_Processors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Machines Running",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: Virtual Machines",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hyperv_hypervisor",
     "select": [
      [
       { "params": [ "Partitions" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Host Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "query": "SELECT mean(\"Percent_User_Time\") AS \"% User Time\" FROM \"win_cpu\" WHERE \"host\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($__interval) fill(linear)",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Processor Time" ], "type": "alias" }
        ],
        [
         { "params": [ "Percent_User_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% User Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Host Available Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: Free Memory",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "query": "SELECT mean(\"Available_Bytes\") as \"Available Bytes\" FROM \"win_mem\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
       "select": [
        [
         { "params": [ "Available_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "$tag_host: Swap Used",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_swap",
       "query": "SELECT mean(\"Available_Bytes\") as \"Available Bytes\" FROM \"win_mem\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
       "select": [
        [
         { "params": [ "Percent_Usage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Virtual Switch Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_instance in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_vswitch",
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$virtual_switch$/" }
       ]
      },
      {
       "alias": "$tag_host: $tag_instance out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_vswitch",
       "select": [
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$virtual_switch$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missed cluster heartbeats",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: Missed heartbeats",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Missing_Cluster_heartbeats",
       "select": [
        [
         { "params": [ "Missing_heartbeats" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "RDMA Network Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 10, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_instance in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "RDMA_Activity",
       "query": "SELECT mean(\"Bytes_Received_persec\") FROM \"hyperv_vmnet\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" =~ /_Network Adapter_/ AND \"instance\" =~ /^$vm_nic$/ AND $timeFilter GROUP BY time($__interval), \"instance\" fill(none)",
       "select": [
        [
         { "params": [ "RDMA_Inbound_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "$tag_host: $tag_instance out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "RDMA_Activity",
       "query": "SELECT mean(\"Bytes_Sent_persec\") FROM \"hyperv_vmnet\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" =~ /_Network Adapter_/ AND \"instance\" =~ /^$vm_nic$/ AND $timeFilter GROUP BY time($__interval), \"instance\" fill(none)",
       "select": [
        [
         { "params": [ "RDMA_Outbound_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "RDMA Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 5, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: Active connections",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "RDMA_Activity",
       "select": [
        [
         { "params": [ "RDMA_Active_Connections" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "$tag_host: Failed connection attempts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "RDMA_Activity",
       "select": [
        [
         {
          "params": [
           "RDMA_Failed_Connection_Attempts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Bytes Sent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: Bytes Sent - $tag_instance",
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "win_net",
       "query": "SELECT last(\"Bytes_Sent_persec\"), last(\"Bytes_Received_persec\") FROM \"win_net\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\"",
       "select": [
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Bytes Received",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: Bytes Received - $tag_instance",
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "win_net",
       "query": "SELECT last(\"Bytes_Sent_persec\"), last(\"Bytes_Received_persec\") FROM \"win_net\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\"",
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Shared FS Performance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_instance read",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cluster_csv_filesystem",
       "select": [
        [
         { "params": [ "Redirected_Read_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
       ]
      },
      {
       "alias": "$tag_instance write",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cluster_csv_filesystem",
       "select": [
        [
         { "params": [ "Redirected_Write_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
       ]
      }
     ]
    },
    {
     "title": "Cluster Shared FS IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance reads/s",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cluster_csv_filesystem",
       "query": "SELECT sum(\"Reads_persec\") FROM \"cluster_csv_filesystem\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^$csv_volume$/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(none)",
       "select": [
        [
         { "params": [ "Reads_persec" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
       ]
      },
      {
       "alias": "$tag_instance writes/s",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cluster_csv_filesystem",
       "select": [
        [
         { "params": [ "Writes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
       ]
      }
     ]
    },
    {
     "title": "Storage Write Latency",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 35 },
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cluster_csv_filesystem",
       "select": [
        [
         { "params": [ "Write_Latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
       ]
      }
     ]
    },
    {
     "title": "Storage Read Latency",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 35 },
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cluster_csv_filesystem",
       "select": [
        [
         { "params": [ "Read_Latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
       ]
      }
     ]
    },
    {
     "title": "Cluster Shared FS Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_instance read",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cluster_csv_filesystem",
       "select": [
        [
         { "params": [ "Read_Latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
       ]
      },
      {
       "alias": "$tag_instance write",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cluster_csv_filesystem",
       "select": [
        [
         { "params": [ "Write_Latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
       ]
      }
     ]
    },
    {
     "title": "DRT Dirty Bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_instance in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Storage_Spaces_Drt",
       "query": "SELECT last(\"Dirty_Bytes\") FROM \"Storage_Spaces_Drt\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"instance\", \"host\" fill(none)",
       "select": [
        [
         { "params": [ "Dirty_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "DRT Limit",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_instance in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Storage_Spaces_Drt",
       "query": "SELECT last(\"Dirty_Bytes\") FROM \"Storage_Spaces_Drt\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"instance\", \"host\" fill(none)",
       "select": [
        [
         { "params": [ "Limit" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "DRT Synchronizing Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_instance in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Storage_Spaces_Drt",
       "query": "SELECT last(\"Dirty_Bytes\") FROM \"Storage_Spaces_Drt\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"instance\", \"host\" fill(none)",
       "select": [
        [
         { "params": [ "Synchronizing_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "CSV Reads /sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "cluster_csv_fs",
       "query": "SELECT mean(\"Reads_persec\") FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s), \"instance\"",
       "select": [
        [
         { "params": [ "Reads_persec" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "CSV Writes /sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "cluster_csv_fs",
       "query": "SELECT \"Disk_Transfers_persec\" FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" > '2') AND $timeFilter GROUP BY \"instance\", \"host\"",
       "select": [
        [
         { "params": [ "Writes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Physical Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host - DiskID: $tag_instance",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "win_diskio",
       "query": "SELECT \"Disk_Transfers_persec\" FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" > '2') AND $timeFilter GROUP BY \"instance\", \"host\"",
       "select": [
        [
         { "params": [ "Disk_Transfers_persec" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^27|28|29|30|31|32/" }
       ]
      }
     ]
    },
    {
     "title": "CSVFS  IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_instance - Reads",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "cluster_csv_fs",
       "query": "SELECT sum(\"Reads_persec\"), sum(\"Writes_persec\") FROM \"cluster_csv_fs\" WHERE (\"instance\" =~ /^$csv_volume$/ AND \"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time(10s), \"instance\"",
       "select": [
        [
         { "params": [ "Reads_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ],
        [
         { "params": [ "Writes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Throughput Reads",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host - DiskID: $tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "win_diskio",
       "query": "SELECT \"Disk_Transfers_persec\" FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" > '2') AND $timeFilter GROUP BY \"instance\", \"host\"",
       "select": [
        [
         { "params": [ "Disk_Read_Bytes_persec" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^27|28|29|30|31|32/" }
       ]
      }
     ]
    },
    {
     "title": "Throughput Writes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host - DiskID: $tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "win_diskio",
       "query": "SELECT \"Disk_Transfers_persec\" FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" > '2') AND $timeFilter GROUP BY \"instance\", \"host\"",
       "select": [
        [
         { "params": [ "Disk_Write_Bytes_persec" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^27|28|29|30|31|32/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "VM Disk Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM Disk Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "query": "SELECT mean(\"Read_Bytes_persec\") FROM \"hyperv_storage\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" =~ /^$vm_disk$/ AND $timeFilter GROUP BY time($__interval), instance fill(none)",
       "select": [
        [
         { "params": [ "Latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "VM Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance reads/s",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "query": "SELECT mean(\"Read_Bytes_persec\") FROM \"hyperv_storage\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" =~ /^$vm_disk$/ AND $timeFilter GROUP BY time($__interval), instance fill(none)",
       "select": [
        [
         { "params": [ "Read_Operations_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/$csv_volume/" }
       ]
      },
      {
       "alias": "$tag_instance writes/s",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "query": "SELECT mean(\"Read_Bytes_persec\") FROM \"hyperv_storage\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" =~ /^$vm_disk$/ AND $timeFilter GROUP BY time($__interval), instance fill(none)",
       "select": [
        [
         { "params": [ "Write_Operations_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/$csv_volume/" }
       ]
      }
     ]
    },
    {
     "title": "VM Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_instance reads/s",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "query": "SELECT mean(\"Read_Bytes_persec\") FROM \"hyperv_storage\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" =~ /^$vm_disk$/ AND $timeFilter GROUP BY time($__interval), instance fill(none)",
       "select": [
        [
         { "params": [ "Read_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/$csv_volume/" }
       ]
      },
      {
       "alias": "$tag_instance writes/s",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "query": "SELECT mean(\"Write_Bytes_persec\") FROM \"hyperv_storage\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" =~ /^$vm_disk$/ AND $timeFilter GROUP BY time($__interval), instance fill(none)",
       "select": [
        [
         { "params": [ "Write_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/$csv_volume/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "VM Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "VM CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hyperv_processor",
     "select": [
      [
       { "params": [ "Percent_Total_Run_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/$virtual_machine/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "VM Memory Used on Hypervisor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hyperv_vid",
     "select": [
      [
       { "params": [ "Physical_Pages_Allocated" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$virtual_machine$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "VM Network Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_instance in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hyperv_vmnet",
     "query": "SELECT mean(\"Bytes_Received_persec\") FROM \"hyperv_vmnet\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" =~ /_Network Adapter_/ AND \"instance\" =~ /^$vm_nic$/ AND $timeFilter GROUP BY time($__interval), \"instance\" fill(none)",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/$virtual_machine/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "$tag_host: $tag_instance out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hyperv_vmnet",
     "query": "SELECT mean(\"Bytes_Sent_persec\") FROM \"hyperv_vmnet\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" =~ /_Network Adapter_/ AND \"instance\" =~ /^$vm_nic$/ AND $timeFilter GROUP BY time($__interval), \"instance\" fill(none)",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/$virtual_machine/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "VM Dynamic Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM Dynamic Memory Pressure",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "hyperv_dynamic_memory",
       "select": [
        [
         { "params": [ "Current_Pressure" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/$virtual_machine/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "VM Guest Visible Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "hyperv_dynamic_memory",
       "select": [
        [
         { "params": [ "Guest_Visible_Physical_Memory" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/$virtual_machine/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}