{
 "title": "Storage Dashboard Small",
 "tags": [
  "windows",
  "hyper-v",
  "vm",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "01,02" },
   {
    "name": "hostname",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"win_system\" WITH KEY = \"host\" WHERE  \"host\" =~ /.*c$cluster.*/"
   },
   {
    "name": "csv_volume",
    "label": "Cluster Volume",
    "query": "SHOW TAG VALUES FROM \"cluster_csv_filesystem\" WITH KEY = \"instance\" WHERE host =~ /$hostname/"
   },
   {
    "name": "virtual_machine",
    "label": "Virtual Machine",
    "query": "SHOW TAG VALUES FROM \"hyperv_vid\" WITH KEY = \"instance\" WHERE \"host\" =~ /^$hostname$/"
   },
   {
    "name": "vm_disk",
    "label": "VM Disk",
    "query": "SHOW TAG VALUES FROM \"hyperv_storage\" WITH KEY = \"instance\" WHERE \"host\" =~ /^$hostname$/"
   },
   {
    "name": "virtual_switch",
    "label": "Virtual Switch",
    "query": "SHOW TAG VALUES FROM \"hyperv_vswitch\" WITH KEY = \"instance\" WHERE host =~ /$hostname/"
   },
   {
    "name": "Interval",
    "label": "Interval",
    "query": "\"$__interval\",10s,30s,1m,5m,10m,15m,30m,1h"
   }
  ]
 },
 "panels": [
  {
   "title": "CSVFS  IOPS Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Reads_persec\") AS \"Reads\", sum(\"Writes_persec\") AS \"Writes\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ],
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Reads_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS  IOPS Per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Reads_persec\") AS \"Reads\", sum(\"Writes_persec\") AS \"Writes\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ],
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Reads_persec\") + sum(\"Writes_persec\") AS \"Total\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval)",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CSVFS  IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance - Reads",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT last(\"Reads_persec\") FROM \"cluster_csv_fs\" WHERE (\"instance\" =~ /^$csv_volume$/ AND \"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval), \"instance\"",
     "select": [
      [
       { "params": [ "Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "$tag_instance - Writes",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT last(\"Writes_persec\") FROM \"cluster_csv_fs\" WHERE (\"instance\" =~ /^$csv_volume$/ AND \"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval), \"instance\"",
     "select": [
      [
       { "params": [ "Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Latency Totals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Reads",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT mean(\"Avg._sec/Read\") FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval) fill(null)",
     "select": [
      [
       { "params": [ "Avg._sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Writes",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT mean(\"Avg._sec/Write\") FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval) fill(null)",
     "select": [
      [
       { "params": [ "Avg._sec/Write" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "cluster_csv_filesystem",
     "query": "SELECT mean(\"Avg._sec/Read\") + mean(\"Avg._sec/Write\") FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval) fill(null)",
     "select": [
      [
       { "params": [ "Write_Latency" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Read Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_instance Read",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT mean(\"Avg._sec/Read\") FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^$csv_volume$/) AND $timeFilter GROUP BY time($Interval), \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "Avg._sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$csv_volume$/" }
     ]
    }
   ]
  },
  {
   "title": "CSVFS Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_instance Write",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT mean(\"Avg._sec/Write\") FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval), \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "Avg._sec/Write" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Space Physical Disk IOPS Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Read IOPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT sum(\"Disk_Reads_persec\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^(?:1(?:)[4-9])|(?:2[0-9])/) AND $timeFilter GROUP BY time($Interval) fill(null)",
     "select": [
      [
       { "params": [ "Disk_Transfers_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Write IOPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT sum(\"Disk_Writes_persec\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^(?:1(?:)[4-9])|(?:2[0-9])/) AND $timeFilter GROUP BY time($Interval) fill(null)",
     "select": [
      [
       { "params": [ "Disk_Transfers_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Space Physical Disk IOPS Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total IOPS",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT sum(\"Disk_Transfers_persec\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^(?:1(?:)[4-9])|(?:2[0-9])/) AND $timeFilter GROUP BY time($Interval) fill(null)",
     "select": [
      [
       { "params": [ "Disk_Transfers_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Space Physical Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT mean(\"Avg._Disk_sec/Transfer\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^(?:1(?:)[4-9])|(?:2[0-9])/) AND $timeFilter GROUP BY time($Interval)",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Transfer" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "!=", "value": "11" }
     ]
    }
   ]
  },
  {
   "title": "Avg Space Physical Disk Latency - Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Reads",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT mean(\"Avg._Disk_sec/Read\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^(?:1(?:)[4-9])|(?:2[0-9])/) AND $timeFilter GROUP BY time($Interval)",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Transfer" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "!=", "value": "11" }
     ]
    }
   ]
  },
  {
   "title": "Avg Space Physical Disk Latency - Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Writes",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT Mean(\"Avg._Disk_sec/Write\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^(?:1(?:)[4-9])|(?:2[0-9])/) AND $timeFilter GROUP BY time($Interval)",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Transfer" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "!=", "value": "11" }
     ]
    }
   ]
  },
  {
   "title": "Space Physical Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_instance",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT last(\"Avg._Disk_sec/Transfer\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^(?:1(?:)[4-9])|(?:2[0-9])/) AND $timeFilter GROUP BY time($Interval), \"instance\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Transfer" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "!=", "value": "11" }
     ]
    }
   ]
  },
  {
   "title": "Space Physical Disk Latency - Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_instance",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT last(\"Avg._Disk_sec/Read\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^(?:1(?:)[4-9])|(?:2[0-9])/) AND $timeFilter GROUP BY time($Interval), \"instance\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Transfer" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "!=", "value": "11" }
     ]
    }
   ]
  },
  {
   "title": "Space Physical Disk Latency - Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_instance",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT last(\"Avg._Disk_sec/Write\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^(?:1(?:)[4-9])|(?:2[0-9])/) AND $timeFilter GROUP BY time($Interval), \"instance\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Transfer" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "!=", "value": "11" }
     ]
    }
   ]
  },
  {
   "title": "Actual Physical Drive Latency Per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT sum(\"Avg._Disk_sec/Transfer\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^(1[0-2]|[0-9])$/) AND $timeFilter GROUP BY time($Interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Transfer" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "12" }
     ]
    }
   ]
  },
  {
   "title": "Actual Physical Drive Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_host - DiskID: $tag_instance",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT last(\"Avg._Disk_sec/Transfer\") FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^(1[0-2]|[0-9])$/) AND $timeFilter GROUP BY time($Interval), \"instance\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Transfer" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "12" }
     ]
    }
   ]
  },
  {
   "title": "CSV Reads Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Read_Bytes_persec\") AS \"Reads\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval) fill(null)",
     "select": [
      [
       { "params": [ "Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CSV Writes Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" }
     ],
     "measurement": "cluster_csv_fs",
     "query": "SELECT sum(\"Write_Bytes_persec\") AS \"Writes\" FROM \"cluster_csv_fs\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval) fill(null)",
     "select": [
      [
       { "params": [ "Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Throughput Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT last(\"Disk_Read_Bytes_persec\") AS \"Reads\" FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval) fill(null)",
     "select": [
      [
       { "params": [ "Disk_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Throughput Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT last(\"Disk_Write_Bytes_persec\") AS \"Writes\" FROM \"win_diskio\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval) fill(null)",
     "select": [
      [
       { "params": [ "Disk_Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}